### ISSUE TITLE
Update GitHub workflow for staged container builds with arm64 support

### ISSUE THREAD

**Issue by toshi0806** [smkwlab/atcoder-container#20]
## 概要

現在のワークフローでは全バリアントを同時にビルドしているが、テスト段階では軽量なLite版のみをビルドし、動作確認後に段階的に他のバリアントもビルドできるよう改善したい。また、arm64版のビルドはarm-runnerで実行するよう最適化する。

### 📋 段階的ビルド戦略
1. **初期テスト段階**: Lite版のみビルド
   - 最軽量 (3.86GB) で動作確認
   - ビルド時間短縮でCI効率化
   
2. **動作確認後**: 全バリアントビルド
   - Lite版 (3.86GB) - 競技プログラミング特化
   - Full版 (8.12GB) - 科学計算・機械学習対応
   - C++専用版 - 将来実装予定 (Issue #18)

### 🏗️ アーキテクチャ別最適化
- **x86_64**: GitHub標準ランナーでビルド
- **arm64**: arm-runnerでビルド（パフォーマンス最適化）

### ワークフロー構成
```yaml
# 段階1: Lite版テストビルド
test-lite:
  strategy:
    matrix:
      arch: [x86_64, arm64]
  runs-on: ${{ matrix.arch == 'arm64' && 'arm-runner' || 'ubuntu-latest' }}
  steps:
    - name: Build Lite Version
      run: docker build -f Dockerfile.lite -t lite:test .

# 段階2: 全バリアント本番ビルド（手動トリガー or 条件付き）
build-all-variants:
  needs: test-lite
  if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build-all]')
  strategy:
    matrix:
      variant: [lite, full]
      arch: [x86_64, arm64]
  runs-on: ${{ matrix.arch == 'arm64' && 'arm-runner' || 'ubuntu-latest' }}
```

### 🎛️ トリガー条件
1. **自動**: PRでLite版のみテストビルド
2. **手動**: `workflow_dispatch`で全バリアントビルド
3. **コミット**: `[build-all]`タグで全バリアントビルド

### ⚡ ビルド時間短縮
- **現在**: 全バリアント同時ビルド（長時間）
- **改善後**: Lite版優先（高速フィードバック）

### 🎯 リソース効率化
- **テスト段階**: 最小限のリソース使用
- **本番段階**: 必要時のみフルビルド

### 🔧 開発体験向上
- **迅速な動作確認**: Lite版での素早い検証
- **段階的デプロイ**: 安全性確保

## 🏷️ 関連Issue
- #17: Full版へのTOMLからC++ライブラリ部分実装 ✅ 完了
- #18: C++専用版Dockerfile.cpp-pro作成 🔄 予定
- #19: マルチステージビルド最適化 🔄 検討中

## 📋 実装チェックリスト
- [ ] ワークフローファイル作成/更新
- [ ] arm-runner設定確認
- [ ] Lite版優先ビルド実装
- [ ] 手動トリガー設定
- [ ] コミットメッセージトリガー実装
- [ ] 段階的ビルド条件設定
- [ ] ドキュメント更新

## 🔖 ラベル
enhancement, ci/cd, docker, performance
