### ISSUE TITLE
Improve GitHub Actions workflow configuration

### ISSUE THREAD

**Issue by toshi0806** [smkwlab/atcoder-container#24]
## 🔧 改善提案

PR #22のマージ後、以下のワークフロー改善を実装する必要があります。

### 1. ワークフローの微調整

**build-staged.yml 79行目付近の条件分岐改善**
```bash
# PRでもfeatureブランチ名を含むものは両プラットフォームビルドを検討
if [[ \"\${{ github.ref_name }}\" == \"main\" || \"\${{ github.ref_name }}\" =~ ^release/ ]]; then
  PLATFORMS=\"linux/amd64,linux/arm64\"
fi
```

### 2. エラーハンドリング強化

**arm-runnerが利用不可の場合の通知追加**
```yaml
- name: Check ARM runner availability
  if: matrix.runner == 'arm-runner'
  run: |
    echo \"::notice::Using ARM runner for native ARM64 build\"
```

### 3. セキュリティ強化

**build-lite action でSLSAサプライチェーン証明書生成**
```yaml
- name: Generate SLSA provenance
  uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.5.0
```

## 🎯 実装優先度

- **High**: ワークフローの微調整（プラットフォーム選択ロジック）
- **Medium**: エラーハンドリング強化
- **Low**: SLSA証明書生成（セキュリティ強化）

## 📝 実装ノート

- 現在のワークフローは基本機能は動作するが、上記改善により運用安定性が向上
- ARM runner可用性チェックは本格運用前に重要
- SLSA証明書はコンテナイメージの供給チェーンセキュリティ向上に寄与
